name: Generate AU GNAF
on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL to GNAF data'
        required: true
        default: 'https://data.gov.au/data/dataset/19432f89-dc3a-4ef3-b943-5326ef1dbecc/resource/4b084096-65e4-4c8e-abbe-5e54ff85f42f/download/may21_gnaf_pipeseparatedvalue.zip'
      tag:
        description: 'Release tag'
        required: true
        default: 'GNAF-2021-05'

jobs:
  checkout_dl:
    runs-on: ubuntu-latest
    container: osgeo/gdal:alpine-ultrasmall-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Download
      id: download
      env:
        DL_PATH: ${{github.event.inputs.url}}
      run: |
        apk add curl unzip sqlite
        mkdir tmp
        curl -L $DL_PATH > data.zip
        unzip data.zip
        mv *_GNAF_*/G-NAF/G-NAF*/Standard tmp/standard
        mv *_GNAF_*/G-NAF/G-NAF*/Authority* tmp/authority
    - name: Create sqlite and geojson
      run: |
        ./bin/gnaf
        ./bin/convert_geojson_gnaf
        ls -l
        gzip gnaf.sqlite
        gzip gnaf.geojson
        ls -l
    - name: Archive GNAF geojson as artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ausgnaf-geojsonseq
        path: gnaf.geojson.gz
    - name: Archive GNAF sqlite as artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ausgnaf-sqlite
        path: gnaf.sqlite.gz
          
  mbtiles:
    runs-on: ubuntu-latest
    container: klokantech/tippecanoe
    needs:
      - checkout_dl
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download AUS geojson from artifacts
        uses: actions/download-artifact@v2
        with:
          name: ausgnaf-geojsonseq
      - name: Download AUS geojson from artifacts
        uses: actions/download-artifact@v2
        with:
          name: ausgnaf-sqlite
      - name: Generate mbtiles
        id: download
        env:
          DL_PATH: ${{github.event.inputs.url}}
        run: |
          ls -l
          gunzip -k gnaf.geojson.gz
          tippecanoe -zg -ab -o gnaf.mbtiles -l "au_gnaf" -n "Geocoded National Address File" -A "Incorporates or developed using G-NAF © Geoscape Australia licensed by the Commonwealth of Australia under the Open Geo-coded National Address File (G-NAF) End User Licence Agreement." -z15 --read-parallel gnaf.geojson
          gzip gnaf.mbtiles

      - name: Archive AUS mbtiles as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ausgnaf-mbtiles
          path: gnaf.mbtiles.gz

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            gnaf.mbtiles.gz
            gnaf.geojson.gz
            gnaf.sqlite.gz
          tag_name: ${{github.event.inputs.tag}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
