name: Generate AU ABS (generic)
on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL to ABS data'
        required: true
        default: 'https://www.abs.gov.au/ausstats/subscriber.nsf/log?openagent&1270055003_poa_2016_aust_shape.zip&1270.0.55.003&Data%20Cubes&4FB811FA48EECA7ACA25802C001432D0&0&July%202016&13.09.2016&Previous'
      fname:
        description: 'File name'
        required: true
        default: 'ABSPOA'
      lid:
        description: 'Layer ID'
        required: true
        default: 'au_abspoa'
      lname:
        description: 'Layer name'
        required: true
        default: 'ABS Postal Area'
      tag:
        description: 'Release tag'
        required: true
        default: 'ABS-2016'

jobs:
  checkout_dl:
    runs-on: ubuntu-latest
    container: osgeo/gdal:alpine-ultrasmall-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Download
      id: download
      env:
        DL_PATH: ${{github.event.inputs.url}}
      run: |
        apk add curl unzip
        mkdir tmp
        curl -L $DL_PATH > data.zip
        unzip data.zip -d tmp/
        ls -l
        ls -l tmp/
    - name: Create geojson
      run: |
        ./bin/convert_geojson_au_abs
        mv tmp/out.geojson ${{github.event.inputs.filename}}.geojson
        gzip ${{github.event.inputs.filename}}.geojson
        ls -l
    - name: Archive AUS geojson as artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{github.event.inputs.filename}}-geojsonseq
        path: ${{github.event.inputs.filename}}.geojson.gz
          
  mbtiles:
    runs-on: ubuntu-latest
    container: klokantech/tippecanoe
    needs:
      - checkout_dl
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download AUS geojson from artifacts
        uses: actions/download-artifact@v2
        with:
          name: ${{github.event.inputs.filename}}-geojsonseq
      - name: Generate mbtiles
        id: download
        env:
          DL_PATH: ${{github.event.inputs.url}}
        run: |
          ls -l
          gunzip -k ${{github.event.inputs.filename}}.geojson.gz
          tippecanoe -zg -ab -o ${{github.event.inputs.filename}}.mbtiles -l "${{github.event.inputs.lid}}" -n "${{github.event.inputs.lname}}" -A "&copy; Australian Bureau of Statistics" --drop-densest-as-needed ${{github.event.inputs.filename}}.geojson
          gzip ${{github.event.inputs.filename}}.mbtiles

      - name: Archive AUS mbtiles as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{github.event.inputs.filename}}-mbtiles
          path: ${{github.event.inputs.filename}}.mbtiles.gz

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{github.event.inputs.filename}}.mbtiles.gz
            ${{github.event.inputs.filename}}.geojson.gz
          tag_name: ${{github.event.inputs.tag}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
