name: Generate AU GNAF
on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL to GNAF data'
        required: true
        default: 'https://data.gov.au/data/dataset/19432f89-dc3a-4ef3-b943-5326ef1dbecc/resource/4b084096-65e4-4c8e-abbe-5e54ff85f42f/download/may21_gnaf_pipeseparatedvalue.zip'
      tag:
        description: 'Release tag'
        required: true
        default: 'GNAF-2021-05-acttest'

jobs:
  checkout_dl:
    runs-on: ubuntu-latest
    container: osgeo/gdal:alpine-small-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Download
      id: download
      env:
        DL_PATH: ${{github.event.inputs.url}}
      run: |
        apk add curl unzip sqlite
        mkdir tmp
        curl -L $DL_PATH > data.zip
        unzip data.zip
        mv G-NAF/G-NAF*/Standard tmp/standard
        mv G-NAF/G-NAF*/Authority* tmp/authority
    - name: Create sqlite and geojson
      run: |
        ls -lh
        ./bin/gnafall
        ls -lh
    - name: Archive GNAF geojson as artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ausgnaf-geojsonseq
        path: gnaf.*.geojson.gz
    - name: Archive GNAF geopackage as artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ausgnaf-gpkg
        path: gnaf.*.gpkg.gz
    - name: Archive GNAF sqlite as artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ausgnaf-sqlite
        path: gnaf.*.sqlite.gz
          
  mbtiles:
    runs-on: ubuntu-latest
    container: klokantech/tippecanoe
    needs:
      - checkout_dl
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download AUS geojson from artifacts
        uses: actions/download-artifact@v2
        with:
          name: ausgnaf-geojsonseq
      - name: Download AUS sqlite from artifacts
        uses: actions/download-artifact@v2
        with:
          name: ausgnaf-sqlite
      - name: Download AUS gpkg from artifacts
        uses: actions/download-artifact@v2
        with:
          name: ausgnaf-gpkg
      - name: Generate mbtiles
        id: download
        env:
          DL_PATH: ${{github.event.inputs.url}}
        run: |
          ls -L
          bin/generate_mbtiles_gnaf ACT &
          bin/generate_mbtiles_gnaf NT &
          bin/generate_mbtiles_gnaf TAS &
          bin/generate_mbtiles_gnaf OT &
          bin/generate_mbtiles_gnaf NSW &
          bin/generate_mbtiles_gnaf QLD &
          bin/generate_mbtiles_gnaf VIC &
          bin/generate_mbtiles_gnaf SA &
          bin/generate_mbtiles_gnaf WA &
          wait
      - name: Archive AUS mbtiles as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ausgnaf-mbtiles
          path: gnaf.*.mbtiles.gz

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            gnaf.ACT.sqlite.gz
            gnaf.NT.sqlite.gz
            gnaf.TAS.sqlite.gz
            gnaf.OT.sqlite.gz
            gnaf.NSW.sqlite.gz
            gnaf.QLD.sqlite.gz
            gnaf.VIC.sqlite.gz
            gnaf.SA.sqlite.gz
            gnaf.WA.sqlite.gz
            gnaf.ACT.geojson.gz
            gnaf.NT.geojson.gz
            gnaf.TAS.geojson.gz
            gnaf.OT.geojson.gz
            gnaf.NSW.geojson.gz
            gnaf.QLD.geojson.gz
            gnaf.VIC.geojson.gz
            gnaf.SA.geojson.gz
            gnaf.WA.geojson.gz
            gnaf.ACT.gpkg.gz
            gnaf.NT.gpkg.gz
            gnaf.TAS.gpkg.gz
            gnaf.OT.gpkg.gz
            gnaf.NSW.gpkg.gz
            gnaf.QLD.gpkg.gz
            gnaf.VIC.gpkg.gz
            gnaf.SA.gpkg.gz
            gnaf.WA.gpkg.gz
            gnaf.ACT.mbtiles.gz
            gnaf.NT.mbtiles.gz
            gnaf.TAS.mbtiles.gz
            gnaf.OT.mbtiles.gz
            gnaf.NSW.mbtiles.gz
            gnaf.QLD.mbtiles.gz
            gnaf.VIC.mbtiles.gz
            gnaf.SA.mbtiles.gz
            gnaf.WA.mbtiles.gz
          tag_name: ${{github.event.inputs.tag}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
