name: Generate AU Localities
on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL to localities data'
        required: true
        default: 'https://github.com/jxeeno/linz-fire-emergency-nz-localities/releases/download/2021-04/lds-fire-and-emergency-nz-localities-SHP.zip'
      tag:
        description: 'Release tag'
        required: true
        default: '2021-04'

jobs:
  checkout_dl:
    runs-on: ubuntu-latest
    container: osgeo/gdal:alpine-ultrasmall-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Download
      id: download
      env:
        DL_PATH: ${{github.event.inputs.url}}
      run: |
        apk add curl unzip
        curl $DL_PATH > data.zip
        mkdir tmp
        unzip data.zip -d tmp/
        ls -l tmp/
    - name: Create geojson
      run: |
        ./bin/convert_geojson_nz
        mv tmp/NZ.geojson NZ.geojson
        gzip NZ.geojson
        ls -l
    - name: Archive NZ geojson as artifacts
      uses: actions/upload-artifact@v2
      with:
        name: nz-geojsonseq
        path: NZ.geojson.gz
          
  mbtiles:
    runs-on: ubuntu-latest
    container: klokantech/tippecanoe
    needs:
      - checkout_dl
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download NZ geojson from artifacts
        uses: actions/download-artifact@v2
        with:
          name: nz-geojsonseq
      - name: Generate mbtiles
        id: download
        env:
          DL_PATH: ${{github.event.inputs.url}}
        run: |
          ls -l
          gunzip -k NZ.geojson.gz
          tippecanoe -zg -ab -o NZ.mbtiles -l "localities" -n "NZ localities" -A "&copy; Fire and Emergency NZ (CC BY 4.0)" --drop-densest-as-needed NZ.geojson
          gzip NZ.mbtiles

      - name: Archive NZ mbtiles as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: nz-mbtiles
          path: NZ.mbtiles.gz

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            NZ.mbtiles.gz
            NZ.geojson.gz
          tag_name: ${{github.event.inputs.tag}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
